# Generated by Django 5.1.4 on 2024-12-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_count', models.CharField(max_length=20)),
                ('about_product', models.TextField()),
                ('img_link', models.URLField(max_length=500)),
                ('product_link', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('review_title', models.CharField(max_length=200)),
                ('review_content', models.TextField()),
                ('review_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='amazon_backend.product')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
