# Generated by Django 5.1.4 on 2024-12-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_backend', '0004_subscription_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_added',
        ),
    ]
