# Generated by Django 5.1.4 on 2024-12-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_backend', '0005_alter_cart_unique_together_alter_cart_product_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='date_added',
        ),
    ]
