# Generated by Django 5.1.4 on 2024-12-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_backend', '0006_alter_wishlist_unique_together_wishlist_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='amazon_backend.vendor'),
        ),
    ]
